const allRoles = {
  admin: [
    'getUsers',
    'manageUsers',
    'getCourses',
    'manageCourses',
    'getSyllabi',
    'manageSyllabi',
    'getModules',
    'manageModules',
    'manageStudents',
    'manageTeachers',
    'getClasses',
    'manageClasses',
    'viewReports',
    'manageSystem',
    'getStudentProgress',
    'manageStudentProgress',
    'getAttendance',
    'manageAttendance',
    'getMRT',
    'manageMRT',
    'uploadFiles',
  ],
  teacher: [
    'getStudents',
    'manageStudents',
    'getCourses',
    'getSyllabi',
    'getModules',
    'getClasses',
    'viewReports',
    'manageAssignments',
    'getStudentProgress',
    'manageStudentProgress',
    'getAttendance',
    'manageAttendance',
    'getMRT',
    'manageMRT',
    'uploadFiles',
  ],
  student: [
    'getStudents',
    'getCourses',
    'getSyllabi',
    'getModules',
    'getClasses',
    'viewAssignments',
    'submitAssignments',
    'viewGrades',
    'getStudentProgress',
    'getAttendance',
    'getMRT',
    'uploadFiles',
  ],
};

export const roles: string[] = Object.keys(allRoles);
export const roleRights: Map<string, string[]> = new Map(Object.entries(allRoles));
